### ISSUE TITLE
Allow paging of results

### ISSUE THREAD

**Issue by chrisprice** [chrisprice/t-d3fc#26]

**Comment by monfera** [comment]
As mentioned in #33, paging would on one hand not really solve the performance degradation present with a bunch of visualizations running at the same time, while paging introduces a large obstacle to browsing, which isn't present with the plain continuous scrolling that's currently in place, so I suggest not doing pagination.

**Comment by chrisprice** [comment]
I've improved the method of starting and stopping animations. I believe this should fix this issue so closing for now. If there are any problems feel free to comment and I can investigate.
