### ISSUE TITLE
Pruning deleted tweets

### ISSUE THREAD

**Issue by monfera** [chrisprice/t-d3fc#28]
Makers may tweet an updated, slightly improved version of some visuals, in which case they might want to (or would even be encouraged to) remove their older version. Or one becomes ashamed of his first wing flaps :-) Currently the removed items stay in the collection (with correct handling of the View Tweet button, which reports that the tweet was deleted).

This autoremove facility would bring author curation, page performance, art diversity and discoverability benefits, at the expense of losing historical accuracy. Maybe, implementationally, it could be good to actually persist the tweet, whether removed or not, but opt to not show it (or show it in much reduced way) if it was deleted. Maybe one year from now it would be interesting to see addition & removal patterns, i.e. worth preserving public facts as they happened.

**Comment by monfera** [comment]
Just retested it, and for removed tweets the button lands on a "Sorry, page doesn't exist" page.

**Comment by chrisprice** [comment]
I've updated the implementation and removed the hack around the 100 tweet limit. For now that means deleted tweets will be removed.

I plan on adding proper storage when I get a chance. At that point features like you've described become possible.

**Comment by chrisprice** [comment]
We're now back to keeping deleted tweets.

**Comment by monfera** [comment]
Indeed, I checked what you said and my old 'mouse X histogram' tweet is still there which I deleted in favor of the minor update I put in early morning. In retrospect it doesn't look like an issue since such updates are rare, and the deletion (hiding) would be more useful on the server side, e.g. for outright copies, empty code/rendering or vandalism. So I think this PR may be closed.

**Comment by chrisprice** [comment]
Ah that's what happened. Joel was showing me that this morning (he sits behind me) and I thought it was a new one but he was amendment it was an old one :smile: 

I'll close this for now, if it becomes a problem I can tackle it then.
