### ISSUE TITLE
Add classes to CSS to enable easier styling

### ISSUE THREAD

**Issue by owennw** [chrisprice/t-d3fc#30]
for example add `.red { fill: 'red'; stroke: 'red'; }` etc.

**Comment by ColinEberhardt** [comment]
I'd be wary of adding too many aliases, this is an API that people have to learn (hopefully with very little effort). you've got a colour scale at your disposal ...

**Comment by owennw** [comment]
I do, but I also only have 116 characters :(

**Comment by chrisprice** [comment]
I think the additional aliases added to the JS and the color scales mean this is no longer required. I also agree with @ColinEberhardt that it's kind of cheating :)
