### ISSUE TITLE
Should new tweets be the default?

### ISSUE THREAD

**Issue by ColinEberhardt** [chrisprice/t-d3fc#31]
When I see a tweets with some code in it, then click the URL, I'd like to see what the code actually produced. It's more likely that the tweet will be near the top of 'new' tweets rather than 'popular'

Ideally the tweet you clicked on would be top of the list.

**Comment by chrisprice** [comment]
Good question. I went with popular to try and down-rank duplicates by default.

**Comment by monfera** [comment]
I think it's a good idea. It doesn't really help with discoverability of older stuff (from RT). To serve linkability to specific tweets, anchors might be useful (the ideal would be putting the code itself as a URL query param but it's not escaped).

**Comment by chrisprice** [comment]
The link format was changed a while ago when the lookup functionality was added. Closing as I think that's solved this issue.
