### ISSUE TITLE
Animation jank issues 

### ISSUE THREAD

**Issue by monfera** [chrisprice/t-d3fc#33]
The tweets are developed in isolation and then go into a large collection. Even with pagination there can be deterioration, and pagination removes from the enjoyment of scrolling through the creations.

A scalable, always zippy solution would be to remove the creations that are not currently visible, or stopping their d3.timer animation and restarting when it becomes visible again.

**Comment by chrisprice** [comment]
Agreed.

Can you let me know where you're seeing this (which page/index) and what you're using to view it (browser/os/device)?
