### ISSUE TITLE
Removal of identical copies

### ISSUE THREAD

**Issue by monfera** [chrisprice/t-d3fc#34]
Some users tweeted identical copies of existing tweets and, because new tweets are more prominent (on twitter as well as on the New page) they collect creds instead of the original work.

**Comment by monfera** [comment]
Identical copies seem to have proliferated over the past few days :-) I wonder if part of it comes from the fork button and users just clicking around, but the retrospective solution might be the filtering of subsequent identical strings, otherwise likes are collected on identical copies.

**Comment by chrisprice** [comment]
Identical copies are now stripped (113d017df703ea9d62318357506c77a64cb39a0a). FYI, there are a number of very minor "variations" which can look like duplicates but are not identical.
