### ISSUE TITLE
Fix back button behavior

### ISSUE THREAD

**Issue by chrisprice** [chrisprice/t-d3fc#40]

**Comment by owennw** [comment]
+1, this is quite annoying (especially on mobile).

**Comment by chrisprice** [comment]
http://stackoverflow.com/a/8681618

**Comment by chrisprice** [comment]
This is trickier than I thought. Dropping priority for now.

**Comment by chrisprice** [comment]
Actually just realised I can just swap the iframe out wholesale for a new one.
