### ISSUE TITLE
Guide?

### ISSUE THREAD

**Issue by Sequoia** [chrisprice/t-d3fc#44]
I love this and want to participate! I'm very confused however, it seems there's lots of magic involved.

e.g.

``` js
C(rn(1,51)).a({r:i=>t/(i*4)%w ...
```

I found `C`, `rn`, and `.a` here: https://github.com/chrisprice/t-d3fc/blob/04f61f4ad6dcecaf5fe1b1d47cd89eec69ef1bb4/public/base.js But I can't figure out where `t` is coming from.

or

``` js
...transform:d=>'scale('+c(_=d+Date.now()/5e3)...
```

I can log `d` & see it's constantly changing each time `transform` is called, but where's it coming from? Will I find this in the D3 docs or is it something added here?

Sorry if these are obvious n00b questions-- like I said I want to do a one but I'm having trouble figuring out what's what! If there were a short list of the globals (outside base.js) or info on what's fed into the render loop or w/e I'd appreciate it!

**Comment by chrisprice** [comment]
I was asked a [similar question on HN](https://news.ycombinator.com/item?id=11028930), I've reproduced my answer below. I'm really keen for people to get involved though, so if there's anything that's still not obvious, please just ask.

> What you see in the tweet is the code which runs in the animation loop. The animation loop is provided, along with all of the abbreviated function aliases, by this base file [1].
> I've reproduced the guts of it below -
> 
> ``` js
>   d3.timer(function(t) {
>     g.d([t]);
>     if (window.tweet) {
>       tweet(t);
>     }
>   });
> ```
> 
> The important bit is the t argument which is provided to the code you see in the tweet. Most of the animations are driven by this value, normally passed through a trigonometric function to provide some easing.
> In the case of my Hello World example, the tweet code is as follows -
> 
> ``` js
>   // Perform a data-join [2] with the parent set to the root node provided 
>   // by the base file, the data defaulting to [t] as above and with a 
>   // built-in behavior of appending an SVG text element in the enter selection.
>   T()
>   // Set the following attributes on the text element -
>   .a({
>     // Affine transform the element using a sc-ale transform.
>     // The scaling value is a function of the data item bound to the element (t).
>     // s is an alias for Math.sin and 1e3 is just shorthand for 1000 (saves 1 character!)
>     transform:d=>sc(4+s(d/1e3)),
>     // Make use of another alias to offset the text based on the normalised mouse position.
>     x:d=>mo[0]*10,
>     y:d=>mo[1]*10
>   })
>   // Set the text content of the text element
>   .t('Hello World')
> ```
> 
> This is by no means an exciting example but it should provide some clues as to how the more complex animations work.
> [1] https://github.com/chrisprice/t-d3fc/blob/master/public/base.js 
> [2] http://bost.ocks.org/mike/join/

**Comment by Sequoia** [comment]
Adding this :point_up_2: plus link to/explanation of `base.js` & maybe a couple links to pertinent pages of d3 docs (which are quite dizzying to search thru) to `README.md` would resolve this issue for me! Does that seem like a good solution?

**Comment by chrisprice** [comment]
It does indeed. I'm adding a couple of enhancements to the site, I'll stick this on the list next.

**Comment by chrisprice** [comment]
I've just published a blog post which covers the above in a little more detail.

**Comment by chrisprice** [comment]
http://blog.scottlogic.com/2016/03/08/deconstructing-a-tweet-sized-d3-creation.html
