### ISSUE TITLE
New gallery is much slower even on strong systems

### ISSUE THREAD

**Issue by bjedrzejewski** [chrisprice/t-d3fc#58]

**Comment by chrisprice** [comment]
Sorry I've just realised I've had notifications turned off for issues. Please can you give more details?

**Comment by chrisprice** [comment]
@bjedrzejewski ?

**Comment by chrisprice** [comment]
Closing due to lack of details

**Comment by bjedrzejewski** [comment]
@chrisprice  Sorry, for the lack of details, I somehow missed the question.

The problem is loading of the gifs I think, they give rather 'choppy' appearance. The performance is actually ok, so it was just my perception.

**Comment by chrisprice** [comment]
I'm open to suggestions on how to improve the perceived performance but it's a compromise of 3 things -
- minimal file size (more frames = bigger file size)
- maximal frame rate (more frames = smoother)
- maximal time range for evolving animations (less fps w/ constant frame count = longer duration)

You can [see the currently configured values here](https://github.com/chrisprice/t-d3fc/blob/3e84d4f0768cbc7615f1c24f3f3eb332d4214387/server/src/gifs.js#L44). It's also quite easy to kick off your own instance of selector-to-gif and run it against the main website.
