### ISSUE TITLE
Suggestion: increase discoverability, shareability

### ISSUE THREAD

**Issue by monfera** [chrisprice/t-d3fc#68]
Similarly to bl.ocks.org, it would be useful to (optionally) incorporate the user ID in the URL of the main page and perhaps the `New` page as a query parameter. It motivates makers to add more pieces, and share existing ones without mixing in other pieces, since currently, they can't review their own stuff like they can on bl.ocks.org or comparable sites.

**Comment by chrisprice** [comment]
https://t.d3fc.io/user/monfera

😄

**Comment by monfera** [comment]
Rad, thank you :-)
